#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.135                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC =  -Iinclude -Ilib/libyuv/include -I../../../../opt/XIMEA/include
CFLAGS =  -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB =  -lfltk /opt/XIMEA/lib/libXIMEA_GenTL.so
LDFLAGS = 

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -g
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG =  $(LDFLAGS)
OBJDIR_DEBUG = obj/debug
DEP_DEBUG = 
OUT_DEBUG = ximea

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -O2
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  $(LDFLAGS) -s
OBJDIR_RELEASE = obj/release
DEP_RELEASE = 
OUT_RELEASE = ximea

OBJ_DEBUG = $(OBJDIR_DEBUG)/lib/libyuv/source/row_posix.o $(OBJDIR_DEBUG)/lib/libyuv/source/convert_argb.o $(OBJDIR_DEBUG)/lib/libyuv/source/convert_from.o $(OBJDIR_DEBUG)/lib/libyuv/source/convert_from_argb.o $(OBJDIR_DEBUG)/lib/libyuv/source/cpu_id.o $(OBJDIR_DEBUG)/lib/libyuv/source/format_conversion.o $(OBJDIR_DEBUG)/lib/libyuv/source/mjpeg_decoder.o $(OBJDIR_DEBUG)/lib/libyuv/source/planar_functions.o $(OBJDIR_DEBUG)/lib/libyuv/source/rotate.o $(OBJDIR_DEBUG)/lib/libyuv/source/rotate_argb.o $(OBJDIR_DEBUG)/lib/libyuv/source/rotate_neon.o $(OBJDIR_DEBUG)/lib/libyuv/source/row_common.o $(OBJDIR_DEBUG)/lib/libyuv/source/row_neon.o $(OBJDIR_DEBUG)/lib/libyuv/source/convert.o $(OBJDIR_DEBUG)/lib/libyuv/source/row_win.o $(OBJDIR_DEBUG)/lib/libyuv/source/scale.o $(OBJDIR_DEBUG)/lib/libyuv/source/scale_argb.o $(OBJDIR_DEBUG)/lib/libyuv/source/scale_neon.o $(OBJDIR_DEBUG)/lib/libyuv/source/video_common.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/src/Camera.o $(OBJDIR_DEBUG)/src/Canvas.o $(OBJDIR_DEBUG)/src/DisplayWindow.o $(OBJDIR_DEBUG)/src/FpsCounter.o $(OBJDIR_DEBUG)/src/Util.o $(OBJDIR_DEBUG)/lib/libyuv/source/compare.o $(OBJDIR_DEBUG)/lib/libyuv/source/compare_neon.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/lib/libyuv/source/row_posix.o $(OBJDIR_RELEASE)/lib/libyuv/source/convert_argb.o $(OBJDIR_RELEASE)/lib/libyuv/source/convert_from.o $(OBJDIR_RELEASE)/lib/libyuv/source/convert_from_argb.o $(OBJDIR_RELEASE)/lib/libyuv/source/cpu_id.o $(OBJDIR_RELEASE)/lib/libyuv/source/format_conversion.o $(OBJDIR_RELEASE)/lib/libyuv/source/mjpeg_decoder.o $(OBJDIR_RELEASE)/lib/libyuv/source/planar_functions.o $(OBJDIR_RELEASE)/lib/libyuv/source/rotate.o $(OBJDIR_RELEASE)/lib/libyuv/source/rotate_argb.o $(OBJDIR_RELEASE)/lib/libyuv/source/rotate_neon.o $(OBJDIR_RELEASE)/lib/libyuv/source/row_common.o $(OBJDIR_RELEASE)/lib/libyuv/source/row_neon.o $(OBJDIR_RELEASE)/lib/libyuv/source/convert.o $(OBJDIR_RELEASE)/lib/libyuv/source/row_win.o $(OBJDIR_RELEASE)/lib/libyuv/source/scale.o $(OBJDIR_RELEASE)/lib/libyuv/source/scale_argb.o $(OBJDIR_RELEASE)/lib/libyuv/source/scale_neon.o $(OBJDIR_RELEASE)/lib/libyuv/source/video_common.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/src/Camera.o $(OBJDIR_RELEASE)/src/Canvas.o $(OBJDIR_RELEASE)/src/DisplayWindow.o $(OBJDIR_RELEASE)/src/FpsCounter.o $(OBJDIR_RELEASE)/src/Util.o $(OBJDIR_RELEASE)/lib/libyuv/source/compare.o $(OBJDIR_RELEASE)/lib/libyuv/source/compare_neon.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d $(OBJDIR_DEBUG)/lib/libyuv/source || mkdir -p $(OBJDIR_DEBUG)/lib/libyuv/source
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LDFLAGS_DEBUG) $(LIBDIR_DEBUG) $(OBJ_DEBUG) $(LIB_DEBUG) -o $(OUT_DEBUG)

$(OBJDIR_DEBUG)/lib/libyuv/source/row_posix.o: lib/libyuv/source/row_posix.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/row_posix.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/row_posix.o

$(OBJDIR_DEBUG)/lib/libyuv/source/convert_argb.o: lib/libyuv/source/convert_argb.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/convert_argb.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/convert_argb.o

$(OBJDIR_DEBUG)/lib/libyuv/source/convert_from.o: lib/libyuv/source/convert_from.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/convert_from.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/convert_from.o

$(OBJDIR_DEBUG)/lib/libyuv/source/convert_from_argb.o: lib/libyuv/source/convert_from_argb.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/convert_from_argb.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/convert_from_argb.o

$(OBJDIR_DEBUG)/lib/libyuv/source/cpu_id.o: lib/libyuv/source/cpu_id.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/cpu_id.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/cpu_id.o

$(OBJDIR_DEBUG)/lib/libyuv/source/format_conversion.o: lib/libyuv/source/format_conversion.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/format_conversion.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/format_conversion.o

$(OBJDIR_DEBUG)/lib/libyuv/source/mjpeg_decoder.o: lib/libyuv/source/mjpeg_decoder.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/mjpeg_decoder.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/mjpeg_decoder.o

$(OBJDIR_DEBUG)/lib/libyuv/source/planar_functions.o: lib/libyuv/source/planar_functions.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/planar_functions.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/planar_functions.o

$(OBJDIR_DEBUG)/lib/libyuv/source/rotate.o: lib/libyuv/source/rotate.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/rotate.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/rotate.o

$(OBJDIR_DEBUG)/lib/libyuv/source/rotate_argb.o: lib/libyuv/source/rotate_argb.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/rotate_argb.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/rotate_argb.o

$(OBJDIR_DEBUG)/lib/libyuv/source/rotate_neon.o: lib/libyuv/source/rotate_neon.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/rotate_neon.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/rotate_neon.o

$(OBJDIR_DEBUG)/lib/libyuv/source/row_common.o: lib/libyuv/source/row_common.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/row_common.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/row_common.o

$(OBJDIR_DEBUG)/lib/libyuv/source/row_neon.o: lib/libyuv/source/row_neon.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/row_neon.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/row_neon.o

$(OBJDIR_DEBUG)/lib/libyuv/source/convert.o: lib/libyuv/source/convert.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/convert.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/convert.o

$(OBJDIR_DEBUG)/lib/libyuv/source/row_win.o: lib/libyuv/source/row_win.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/row_win.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/row_win.o

$(OBJDIR_DEBUG)/lib/libyuv/source/scale.o: lib/libyuv/source/scale.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/scale.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/scale.o

$(OBJDIR_DEBUG)/lib/libyuv/source/scale_argb.o: lib/libyuv/source/scale_argb.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/scale_argb.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/scale_argb.o

$(OBJDIR_DEBUG)/lib/libyuv/source/scale_neon.o: lib/libyuv/source/scale_neon.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/scale_neon.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/scale_neon.o

$(OBJDIR_DEBUG)/lib/libyuv/source/video_common.o: lib/libyuv/source/video_common.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/video_common.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/video_common.o

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/src/Camera.o: src/Camera.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Camera.cpp -o $(OBJDIR_DEBUG)/src/Camera.o

$(OBJDIR_DEBUG)/src/Canvas.o: src/Canvas.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Canvas.cpp -o $(OBJDIR_DEBUG)/src/Canvas.o

$(OBJDIR_DEBUG)/src/DisplayWindow.o: src/DisplayWindow.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DisplayWindow.cpp -o $(OBJDIR_DEBUG)/src/DisplayWindow.o

$(OBJDIR_DEBUG)/src/FpsCounter.o: src/FpsCounter.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/FpsCounter.cpp -o $(OBJDIR_DEBUG)/src/FpsCounter.o

$(OBJDIR_DEBUG)/src/Util.o: src/Util.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Util.cpp -o $(OBJDIR_DEBUG)/src/Util.o

$(OBJDIR_DEBUG)/lib/libyuv/source/compare.o: lib/libyuv/source/compare.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/compare.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/compare.o

$(OBJDIR_DEBUG)/lib/libyuv/source/compare_neon.o: lib/libyuv/source/compare_neon.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/libyuv/source/compare_neon.cc -o $(OBJDIR_DEBUG)/lib/libyuv/source/compare_neon.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/lib/libyuv/source
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d $(OBJDIR_RELEASE)/lib/libyuv/source || mkdir -p $(OBJDIR_RELEASE)/lib/libyuv/source
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LDFLAGS_RELEASE) $(LIBDIR_RELEASE) $(OBJ_RELEASE) $(LIB_RELEASE) -o $(OUT_RELEASE)

$(OBJDIR_RELEASE)/lib/libyuv/source/row_posix.o: lib/libyuv/source/row_posix.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/row_posix.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/row_posix.o

$(OBJDIR_RELEASE)/lib/libyuv/source/convert_argb.o: lib/libyuv/source/convert_argb.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/convert_argb.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/convert_argb.o

$(OBJDIR_RELEASE)/lib/libyuv/source/convert_from.o: lib/libyuv/source/convert_from.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/convert_from.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/convert_from.o

$(OBJDIR_RELEASE)/lib/libyuv/source/convert_from_argb.o: lib/libyuv/source/convert_from_argb.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/convert_from_argb.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/convert_from_argb.o

$(OBJDIR_RELEASE)/lib/libyuv/source/cpu_id.o: lib/libyuv/source/cpu_id.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/cpu_id.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/cpu_id.o

$(OBJDIR_RELEASE)/lib/libyuv/source/format_conversion.o: lib/libyuv/source/format_conversion.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/format_conversion.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/format_conversion.o

$(OBJDIR_RELEASE)/lib/libyuv/source/mjpeg_decoder.o: lib/libyuv/source/mjpeg_decoder.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/mjpeg_decoder.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/mjpeg_decoder.o

$(OBJDIR_RELEASE)/lib/libyuv/source/planar_functions.o: lib/libyuv/source/planar_functions.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/planar_functions.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/planar_functions.o

$(OBJDIR_RELEASE)/lib/libyuv/source/rotate.o: lib/libyuv/source/rotate.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/rotate.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/rotate.o

$(OBJDIR_RELEASE)/lib/libyuv/source/rotate_argb.o: lib/libyuv/source/rotate_argb.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/rotate_argb.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/rotate_argb.o

$(OBJDIR_RELEASE)/lib/libyuv/source/rotate_neon.o: lib/libyuv/source/rotate_neon.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/rotate_neon.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/rotate_neon.o

$(OBJDIR_RELEASE)/lib/libyuv/source/row_common.o: lib/libyuv/source/row_common.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/row_common.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/row_common.o

$(OBJDIR_RELEASE)/lib/libyuv/source/row_neon.o: lib/libyuv/source/row_neon.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/row_neon.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/row_neon.o

$(OBJDIR_RELEASE)/lib/libyuv/source/convert.o: lib/libyuv/source/convert.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/convert.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/convert.o

$(OBJDIR_RELEASE)/lib/libyuv/source/row_win.o: lib/libyuv/source/row_win.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/row_win.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/row_win.o

$(OBJDIR_RELEASE)/lib/libyuv/source/scale.o: lib/libyuv/source/scale.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/scale.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/scale.o

$(OBJDIR_RELEASE)/lib/libyuv/source/scale_argb.o: lib/libyuv/source/scale_argb.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/scale_argb.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/scale_argb.o

$(OBJDIR_RELEASE)/lib/libyuv/source/scale_neon.o: lib/libyuv/source/scale_neon.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/scale_neon.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/scale_neon.o

$(OBJDIR_RELEASE)/lib/libyuv/source/video_common.o: lib/libyuv/source/video_common.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/video_common.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/video_common.o

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/src/Camera.o: src/Camera.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Camera.cpp -o $(OBJDIR_RELEASE)/src/Camera.o

$(OBJDIR_RELEASE)/src/Canvas.o: src/Canvas.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Canvas.cpp -o $(OBJDIR_RELEASE)/src/Canvas.o

$(OBJDIR_RELEASE)/src/DisplayWindow.o: src/DisplayWindow.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DisplayWindow.cpp -o $(OBJDIR_RELEASE)/src/DisplayWindow.o

$(OBJDIR_RELEASE)/src/FpsCounter.o: src/FpsCounter.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/FpsCounter.cpp -o $(OBJDIR_RELEASE)/src/FpsCounter.o

$(OBJDIR_RELEASE)/src/Util.o: src/Util.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Util.cpp -o $(OBJDIR_RELEASE)/src/Util.o

$(OBJDIR_RELEASE)/lib/libyuv/source/compare.o: lib/libyuv/source/compare.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/compare.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/compare.o

$(OBJDIR_RELEASE)/lib/libyuv/source/compare_neon.o: lib/libyuv/source/compare_neon.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/libyuv/source/compare_neon.cc -o $(OBJDIR_RELEASE)/lib/libyuv/source/compare_neon.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/lib/libyuv/source
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

